### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by AK1529498121** [IshitaTakeshi/PCANet#10]
when  I run run_mnist.py,an error occurred :Traceback (most recent call last):
  File "D:/1-Myprojects/python/PCANet/my_test.py", line 50, in <module>
    pcanet.fit(images_train)  # Train PCANet
  File "D:\1-Myprojects\python\PCANet\pcanet.py", line 353, in fit
    self.pca_l2.partial_fit(patches)
  File "D:\anaconda3\envs\tensorflow\lib\site-packages\sklearn\decomposition\incremental_pca.py", line 279, in partial_fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File "D:\anaconda3\envs\tensorflow\lib\site-packages\scipy\linalg\decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "D:\anaconda3\envs\tensorflow\lib\site-packages\scipy\_lib\_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "C:\Users\Dell\AppData\Roaming\Python\Python35\site-packages\numpy\lib\function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

when I run pcanet.fit(images_train) with my data set, no error. But when I change the size of my data set, the same error occurred.Have you ever met this problem before ? Thank you for your help.

**Comment by xankegongge** [comment]
I have the same problem.  Have you solved this problem?

**Comment by IshitaTakeshi** [comment]
Could you insert `print(images)` to this line and show me the result?

https://github.com/IshitaTakeshi/PCANet/blob/master/pcanet.py#L346
