### ISSUE TITLE
Memory Error in PCANet for CIFAR10 DATASET

### ISSUE THREAD

**Issue by arunadevikaruppasamy** [IshitaTakeshi/PCANet#5]
while running CIFAR10 dataset, memory error occurred.
I have attached the following error message
Can you guide me to resolve this issue?. Thank you

######################################################################33
Downloading from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz...
Training the model...
Training PCANet
Traceback (most recent call last):
  File "run_cifar_aruna.py", line 82, in <module>
    pcanet, classifier = train(train_set)
  File "run_cifar_aruna.py", line 48, in train
    pcanet.fit(images_train)
  File "/home/phd/Downloads/PCANet-master/pcanet.py", line 337, in fit
    stride=self.step_shape_l1
  File "/usr/local/lib/python3.6/dist-packages/chainer-6.0.0b2-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 581, in convolution_2d
    y, = fnode.apply(args)
  File "/usr/local/lib/python3.6/dist-packages/chainer-6.0.0b2-py3.6.egg/chainer/function_node.py", line 318, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.6/dist-packages/chainer-6.0.0b2-py3.6.egg/chainer/function_node.py", line 506, in forward
    return self.forward_cpu(inputs)
  File "/usr/local/lib/python3.6/dist-packages/chainer-6.0.0b2-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 123, in forward_cpu
    return self._forward_cpu_core(x, W, b)
  File "/usr/local/lib/python3.6/dist-packages/chainer-6.0.0b2-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 134, in _forward_cpu_core
    col, W, ((1, 2, 3), (1, 2, 3))).astype(x.dtype, copy=False)
  File "/usr/lib/python3/dist-packages/numpy/core/numeric.py", line 1339, in tensordot
    res = dot(at, bt)
MemoryError

**Comment by IshitaTakeshi** [comment]
PCANet has a disadvantage that it requires all samples in data at training.
However in this implementation, Incremental PCA is used instead of the ordinal PCA.
Therefore still works if you replace 

```
    pcanet.fit(images_train)
```

in `run_mnist.py` with

```
    for n in range(0, len(images_train), 100):
        print("Running", n)
        pcanet.fit(images_train[n:n+100])
```

**Comment by arunadevikaruppasamy** [comment]
i modified  the program but again i m getting the same memory error. Could you please help me to resolve it

**Comment by arunadevikaruppasamy** [comment]
I tried the following statement to use original PCA
If you want to run it on the ordinary PCA, just replace IncrementalPCA with sklearn.decomposition.PCA.


i m getting the following error 
phd@hp-prodesk-600:~/Downloads/PCANet-master$ python3 run_mnist_small_aruna.py --gpu -1 train --out aruna_small_results
Using TensorFlow backend.
Training the model...
Training PCANet
Traceback (most recent call last):
  File "run_mnist_small_aruna.py", line 161, in <module>
    pcanet, classifier = train()
  File "run_mnist_small_aruna.py", line 91, in train
    pcanet.fit(images_train)
  File "/home/phd/Downloads/PCANet-master/pcanet.py", line 322, in fit
    self.pca_l1.partial_fit(patches)
AttributeError: 'PCA' object has no attribute 'partial_fit'

**Comment by IshitaTakeshi** [comment]
Decrease the batch size and buy DRAM if the same error showed again

```
    for n in range(0, len(images_train), 10):
        pcanet.fit(images_train[n:n+10])
```

**Comment by arunadevikaruppasamy** [comment]
it is working now. Thank you.
